languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "AWS IoT Device Defender Workshop"
theme = "learn"
uglyurls = true
googleAnalytics = "G-Z8CD30SWK9"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
editURL = "https://github.com/reisjr/aws-iot-labguide/tree/master/content/"
themeVariant = "mine"
showVisitedLinks = false
author = "David Reis, Giovani Bassan"
description = "AWS IoT Builders Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
ghrepo = "TBD"
branch = "master"
template_bucket = "eksworkshop.com"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "tango"

#

[menu]

[[menu.main]]
identifier = "Prerequisites"
name = "This is the Mu track"
title = "Workshop using Mu"
url = "/mu/"
weight = -110

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> More Resources"
url = "/more_resources.html"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "/authors.html"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/TBD"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> IoT Device Mgmt - GitHub"
url = "https://github.com/gbassan-br/iot-mgmt-builders"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "mailto:awsiotddworkshop@amazon.com"
weight = 40

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
name = "default"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://gobuild.today?region=us-east-1"

[[deployment.targets]]
name = "gbassan"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://gbassan-builders-iot?region=us-east-1"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
